# Generated by Django 3.2.12 on 2023-03-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_trext',
            new_name='question_text',
        ),
    ]
